version: "3"

services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: trell
    container_name: trell-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - trell

  db:
    image: mysql:8.0
    container_name: trell-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      # - ./docker-compose/mysqlconf/my.conf:/etc/my.conf:z
    networks:
      - trell
    ports:
      - "3306:3306"

  nginx:
    image: nginx:alpine
    container_name: trell-nginx
    restart: unless-stopped
    ports:
      - 8111:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - trell

networks:
  trell:
    driver: bridge