<?php

defined('REASON_TYPE_DAILY_RICE') or define('REASON_TYPE_DAILY_RICE', 'DAILY_RICE');
defined('REASON_TYPE_OTHER') or define('REASON_TYPE_OTHER', 'OTHER');

defined('REASON_DAILY_RICE') or define('REASON_DAILY_RICE', 'TRU PHI THUC AN HANG NGAY');
defined('REASON_EDIT_USER_BALANCE') or define('REASON_EDIT_USER_BALANCE', 'CAP NHAT SO DU MOT TAI KHOAN');

defined('USER_ROLE_ADMIN') or define('USER_ROLE_ADMIN', 'admin');
defined('USER_ROLE_USER') or define('USER_ROLE_USER', 'user');
defined('USER_ROLE_VISITOR') or define('USER_ROLE_VISITOR', 'visitor');

defined('FAKE_USER_NAME') or define('FAKE_USER_NAME', 'fakeUser1');

defined('DEFAULT_LOGIN_CODE') or define('DEFAULT_LOGIN_CODE', '164331');

defined('PAYMENT_STATUS_WAITING') or define('PAYMENT_STATUS_WAITING', 'WAITING');
defined('PAYMENT_STATUS_PAID') or define('PAYMENT_STATUS_PAID', 'PAID');

defined('DELIVERY_STATUS_REQUEST') or define('DELIVERY_STATUS_REQUEST', 'REQUEST');
defined('DELIVERY_STATUS_CONFIRMED') or define('DELIVERY_STATUS_CONFIRMED', 'CONFIRMED');
defined('DELIVERY_STATUS_DELIVERING') or define('DELIVERY_STATUS_DELIVERING', 'DELIVERING');
defined('DELIVERY_STATUS_DELIVERED') or define('DELIVERY_STATUS_DELIVERED', 'DELIVERED');
defined('DELIVERY_STATUS_CANCELED') or define('DELIVERY_STATUS_CANCELED', 'CANCELED');
