<?php

defined('REASON_TYPE_DAILY_RICE') or define('REASON_TYPE_DAILY_RICE', 'DAILY_RICE');
defined('REASON_TYPE_OTHER') or define('REASON_TYPE_OTHER', 'OTHER');

defined('REASON_DAILY_RICE') or define('REASON_DAILY_RICE', 'TRU PHI THUC AN HANG NGAY');
defined('REASON_EDIT_USER_BALANCE') or define('REASON_EDIT_USER_BALANCE', 'CAP NHAT SO DU MOT TAI KHOAN');
